# Generated by Django 4.2.2 on 2023-09-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('specialist', models.CharField(max_length=100)),
                ('doctor_fees', models.DecimalField(decimal_places=2, max_digits=5)),
                ('doctor_schedule', models.CharField(max_length=50)),
                ('doctor_img', models.ImageField(upload_to='doctor_img/')),
                ('doctor_loc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('medcine_about', models.CharField(max_length=100)),
                ('medicine_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medicine_img', models.ImageField(upload_to='medicine_img/')),
                ('medicine_des', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_head', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('news_link', models.CharField(max_length=100)),
                ('news_des', models.CharField(max_length=500)),
            ],
        ),
    ]
