# Generated by Django 4.2.2 on 2023-10-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENGUE_APP', '0003_news_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.ImageField(upload_to='news_img/'),
        ),
    ]
