# Generated by Django 4.2.2 on 2023-10-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENGUE_APP', '0004_alter_news_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
