# Generated by Django 4.2.2 on 2023-10-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENGUE_APP', '0006_alter_news_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_des',
            field=models.CharField(max_length=2000),
        ),
    ]
