# Generated by Django 5.0.6 on 2024-07-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENGUE_APP', '0007_alter_news_news_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('mailid', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='userlog',
        ),
    ]
