# Generated by Django 5.0.6 on 2024-07-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DENGUE_APP', '0008_userdet_delete_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='link1',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='link2',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='link3',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
